M

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -467,7 +467,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CYGWIN_TRUE CYGWIN_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LN_S ECHO RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP EGREP LIBTOOL CXX CXXFLAGS ac_ct_CXX MAJOR_VERSION MINOR_VERSION PATCH_LEVEL INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh INSTALL_STRIP_PROGRAM AWK SET_MAKE DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LT_FXSCINTILLA_CURRENT LT_FXSCINTILLA_REVISION LT_FXSCINTILLA_AGE LT_FXSCINTILLANOLEXER_CURRENT LT_FXSCINTILLANOLEXER_REVISION LT_FXSCINTILLANOLEXER_AGE NOLEXER_TRUE NOLEXER_FALSE CXXCPP PTHREAD_CC PTHREAD_LIBS PTHREAD_CFLAGS FOX_INCLUDE_DIR FOX_LIB_DIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os HAVE_CYGWIN_TRUE HAVE_CYGWIN_FALSE HAVE_MINGW32_TRUE HAVE_MINGW32_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LN_S ECHO RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP EGREP LIBTOOL CXX CXXFLAGS ac_ct_CXX MAJOR_VERSION MINOR_VERSION PATCH_LEVEL INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh INSTALL_STRIP_PROGRAM AWK SET_MAKE DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LT_FXSCINTILLA_CURRENT LT_FXSCINTILLA_REVISION LT_FXSCINTILLA_AGE LT_FXSCINTILLANOLEXER_CURRENT LT_FXSCINTILLANOLEXER_REVISION LT_FXSCINTILLANOLEXER_AGE NOLEXER_TRUE NOLEXER_FALSE CXXCPP PTHREAD_CC PTHREAD_LIBS PTHREAD_CFLAGS FOX_INCLUDE_DIR FOX_LIB_DIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1534,22 +1534,33 @@ host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 
 
 case $host_os in
-  *cygwin* ) CYGWIN=yes;;
-         * ) CYGWIN=no;;
+	*cygwin* )  HAVE_CYGWIN=yes;;
+	*mingw32* ) HAVE_MINGW32=yes;;
+	* ) ;;
 esac
 
 
 
-if test x"$CYGWIN" = xyes; then
-  CYGWIN_TRUE=
-  CYGWIN_FALSE='#'
+if test x"$HAVE_CYGWIN" = xyes; then
+  HAVE_CYGWIN_TRUE=
+  HAVE_CYGWIN_FALSE='#'
 else
-  CYGWIN_TRUE='#'
-  CYGWIN_FALSE=
+  HAVE_CYGWIN_TRUE='#'
+  HAVE_CYGWIN_FALSE=
 fi
 
 
-if test x"$CYGWIN" = xyes; then
+
+if test x"$HAVE_MINGW32" = xyes; then
+  HAVE_MINGW32_TRUE=
+  HAVE_MINGW32_FALSE='#'
+else
+  HAVE_MINGW32_TRUE='#'
+  HAVE_MINGW32_FALSE=
+fi
+
+
+if test x"$HAVE_CYGWIN" = xyes -o x"$HAVE_MINGW32" = xyes; then
   # Check whether --enable-shared or --disable-shared was given.
 if test "${enable_shared+set}" = set; then
   enableval="$enable_shared"
@@ -4066,7 +4077,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4069 "configure"' > conftest.$ac_ext
+  echo '#line 4080 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4595,7 +4606,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:4598: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:4609: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6419,7 +6430,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6422 "configure"
+#line 6433 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6517,7 +6528,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6520 "configure"
+#line 6531 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8443,22 +8454,13 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
 #
-# Checking for Cygwin
+# Checking for Cygwin and MinGW32
 #
 case $host_os in
-  *cygwin* ) CYGWIN=yes;;
-         * ) CYGWIN=no;;
+  *cygwin* ) HAVE_CYGWIN=yes;;
+  *mingw32* ) HAVE_MINGW32=yes;;
+         * ) ;;
 esac
-
-
-if test x"$CYGWIN" = xyes; then
-  CYGWIN_TRUE=
-  CYGWIN_FALSE='#'
-else
-  CYGWIN_TRUE='#'
-  CYGWIN_FALSE=
-fi
-
 #
 # Handle user hints
 #
@@ -8501,9 +8503,11 @@ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ex
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
-if test x"$CYGWIN" = xyes; then
-	CPPFLAGS="$CPPFLAGS -DWIN32"
+if test x"$HAVE_CYGWIN" = xyes -o x"$HAVE_MINGW32" = xyes; then
   LDFLAGS="$LDFLAGS -mwindows"
+	if test x"$HAVE_CYGWIN" = xyes; then
+		CPPFLAGS="$CPPFLAGS -DWIN32"
+	fi
 fi
 
 #
@@ -9480,10 +9484,17 @@ LIBOBJS=$ac_libobjs
 LTLIBOBJS=$ac_ltlibobjs
 
 
-if test -z "${CYGWIN_TRUE}" && test -z "${CYGWIN_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"CYGWIN\" was never defined.
+if test -z "${HAVE_CYGWIN_TRUE}" && test -z "${HAVE_CYGWIN_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_CYGWIN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"CYGWIN\" was never defined.
+echo "$as_me: error: conditional \"HAVE_CYGWIN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_MINGW32_TRUE}" && test -z "${HAVE_MINGW32_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_MINGW32\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_MINGW32\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -9512,13 +9523,6 @@ if test -z "${NOLEXER_TRUE}" && test -z "${NOLEXER_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"NOLEXER\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"NOLEXER\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test -z "${CYGWIN_TRUE}" && test -z "${CYGWIN_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"CYGWIN\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"CYGWIN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -10059,8 +10063,10 @@ s,@host@,$host,;t t
 s,@host_cpu@,$host_cpu,;t t
 s,@host_vendor@,$host_vendor,;t t
 s,@host_os@,$host_os,;t t
-s,@CYGWIN_TRUE@,$CYGWIN_TRUE,;t t
-s,@CYGWIN_FALSE@,$CYGWIN_FALSE,;t t
+s,@HAVE_CYGWIN_TRUE@,$HAVE_CYGWIN_TRUE,;t t
+s,@HAVE_CYGWIN_FALSE@,$HAVE_CYGWIN_FALSE,;t t
+s,@HAVE_MINGW32_TRUE@,$HAVE_MINGW32_TRUE,;t t
+s,@HAVE_MINGW32_FALSE@,$HAVE_MINGW32_FALSE,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
