Compatibility with FOX 1.1 branch.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5175,7 +5175,7 @@ fi
 
 MAJOR_VERSION=1
 MINOR_VERSION=46
-PATCH_LEVEL=1
+PATCH_LEVEL=2
 
 
 
@@ -5643,16 +5643,16 @@ CXXDEPMODE="depmode=$am_cv_CXX_dependencies_compiler_type"
 
 
 
-LT_FXSCINTILLA_CURRENT=1
+LT_FXSCINTILLA_CURRENT=2
 LT_FXSCINTILLA_REVISION=0
-LT_FXSCINTILLA_AGE=1
+LT_FXSCINTILLA_AGE=2
 
 
 
 
-LT_FXSCINTILLANOLEXER_CURRENT=0
+LT_FXSCINTILLANOLEXER_CURRENT=1
 LT_FXSCINTILLANOLEXER_REVISION=0
-LT_FXSCINTILLANOLEXER_AGE=0
+LT_FXSCINTILLANOLEXER_AGE=1
 
 
 
@@ -5678,13 +5678,10 @@ else
   NOLEXER_FALSE=
 fi
 
-# 1 = FOX MAJOR VERSION
-# 0 = FOX_MINOR_VERSION
 
 #
 # Handle user hints
 #
-
 # Check whether --with-foxinclude or --without-foxinclude was given.
 if test "${with_foxinclude+set}" = set; then
   withval="$with_foxinclude"
@@ -5727,17 +5724,17 @@ cross_compiling=$ac_cv_prog_cc_cross
 #
 ac_safe=`echo "fox/fx.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for fox/fx.h""... $ac_c" 1>&6
-echo "configure:5731: checking for fox/fx.h" >&5
+echo "configure:5728: checking for fox/fx.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 5736 "configure"
+#line 5733 "configure"
 #include "confdefs.h"
 #include <fox/fx.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:5741: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:5738: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -5764,9 +5761,9 @@ fi
 # Check FOX lib without pthread
 #
 echo $ac_n "checking for FOX library""... $ac_c" 1>&6
-echo "configure:5768: checking for FOX library" >&5
+echo "configure:5765: checking for FOX library" >&5
 cat > conftest.$ac_ext <<EOF
-#line 5770 "configure"
+#line 5767 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -5777,7 +5774,7 @@ int main() {
 fxfindfox()
 ; return 0; }
 EOF
-if { (eval echo configure:5781: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:5778: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   have_FOX=yes
 else
@@ -5811,9 +5808,9 @@ if test x"$PTHREAD_LIBS$PTHREAD_CFLAGS" != x; then
         save_LIBS="$LIBS"
         LIBS="$PTHREAD_LIBS $LIBS"
         echo $ac_n "checking for pthread_join in LIBS=$PTHREAD_LIBS with CFLAGS=$PTHREAD_CFLAGS""... $ac_c" 1>&6
-echo "configure:5815: checking for pthread_join in LIBS=$PTHREAD_LIBS with CFLAGS=$PTHREAD_CFLAGS" >&5
+echo "configure:5812: checking for pthread_join in LIBS=$PTHREAD_LIBS with CFLAGS=$PTHREAD_CFLAGS" >&5
         cat > conftest.$ac_ext <<EOF
-#line 5817 "configure"
+#line 5814 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -5824,7 +5821,7 @@ int main() {
 pthread_join()
 ; return 0; }
 EOF
-if { (eval echo configure:5828: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:5825: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   acx_pthread_ok=yes
 else
@@ -5891,18 +5888,18 @@ for flag in $acx_pthread_flags; do
         case $flag in
                 none)
                 echo $ac_n "checking whether pthreads work without any flags""... $ac_c" 1>&6
-echo "configure:5895: checking whether pthreads work without any flags" >&5
+echo "configure:5892: checking whether pthreads work without any flags" >&5
                 ;;
 
                 -*)
                 echo $ac_n "checking whether pthreads work with $flag""... $ac_c" 1>&6
-echo "configure:5900: checking whether pthreads work with $flag" >&5
+echo "configure:5897: checking whether pthreads work with $flag" >&5
                 PTHREAD_CFLAGS="$flag"
                 ;;
 
                 *)
                 echo $ac_n "checking for the pthreads library -l$flag""... $ac_c" 1>&6
-echo "configure:5906: checking for the pthreads library -l$flag" >&5
+echo "configure:5903: checking for the pthreads library -l$flag" >&5
                 PTHREAD_LIBS="-l$flag"
                 ;;
         esac
@@ -5922,7 +5919,7 @@ echo "configure:5906: checking for the pthreads library -l$flag" >&5
         # functions on Solaris that doesn't have a non-functional libc stub.
         # We try pthread_create on general principles.
         cat > conftest.$ac_ext <<EOF
-#line 5926 "configure"
+#line 5923 "configure"
 #include "confdefs.h"
 #include <pthread.h>
 int main() {
@@ -5931,7 +5928,7 @@ pthread_t th; pthread_join(th, 0);
                      pthread_create(0,0,0,0); pthread_cleanup_pop(0); 
 ; return 0; }
 EOF
-if { (eval echo configure:5935: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:5932: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   acx_pthread_ok=yes
 else
@@ -5963,16 +5960,16 @@ if test "x$acx_pthread_ok" = xyes; then
         # Detect AIX lossage: threads are created detached by default
         # and the JOINABLE attribute has a nonstandard name (UNDETACHED).
         echo $ac_n "checking for joinable pthread attribute""... $ac_c" 1>&6
-echo "configure:5967: checking for joinable pthread attribute" >&5
+echo "configure:5964: checking for joinable pthread attribute" >&5
         cat > conftest.$ac_ext <<EOF
-#line 5969 "configure"
+#line 5966 "configure"
 #include "confdefs.h"
 #include <pthread.h>
 int main() {
 int attr=PTHREAD_CREATE_JOINABLE;
 ; return 0; }
 EOF
-if { (eval echo configure:5976: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:5973: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   ok=PTHREAD_CREATE_JOINABLE
 else
@@ -5984,14 +5981,14 @@ fi
 rm -f conftest*
         if test x"$ok" = xunknown; then
                 cat > conftest.$ac_ext <<EOF
-#line 5988 "configure"
+#line 5985 "configure"
 #include "confdefs.h"
 #include <pthread.h>
 int main() {
 int attr=PTHREAD_CREATE_UNDETACHED;
 ; return 0; }
 EOF
-if { (eval echo configure:5995: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:5992: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   ok=PTHREAD_CREATE_UNDETACHED
 else
@@ -6014,7 +6011,7 @@ EOF
         fi
 
         echo $ac_n "checking if more special flags are required for pthreads""... $ac_c" 1>&6
-echo "configure:6018: checking if more special flags are required for pthreads" >&5
+echo "configure:6015: checking if more special flags are required for pthreads" >&5
         flag=no
         case "${host_cpu}-${host_os}" in
                 *-aix* | *-freebsd*)     flag="-D_THREAD_SAFE";;
@@ -6032,7 +6029,7 @@ echo "configure:6018: checking if more special flags are required for pthreads" 
         # Extract the first word of "cc_r", so it can be a program name with args.
 set dummy cc_r; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:6036: checking for $ac_word" >&5
+echo "configure:6033: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_PTHREAD_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -6082,9 +6079,9 @@ fi
 
 	CPPFLAGS="$PTHREAD_CFLAGS $CPPFLAGS"
   echo $ac_n "checking for FOX library with pthread""... $ac_c" 1>&6
-echo "configure:6086: checking for FOX library with pthread" >&5
+echo "configure:6083: checking for FOX library with pthread" >&5
   cat > conftest.$ac_ext <<EOF
-#line 6088 "configure"
+#line 6085 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -6095,7 +6092,7 @@ int main() {
 fxfindfox()
 ; return 0; }
 EOF
-if { (eval echo configure:6099: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:6096: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   have_FOX=yes
 else
@@ -6117,37 +6114,6 @@ if test x"$have_FOX" = xno; then
 fi
 
 #
-# Check Fox version
-#
-echo $ac_n "checking FOX version 1.0.x""... $ac_c" 1>&6
-echo "configure:6124: checking FOX version 1.0.x" >&5
-if test "$cross_compiling" = yes; then
-  echo "configure: warning: Cross compiling" 1>&2
-else
-  cat > conftest.$ac_ext <<EOF
-#line 6129 "configure"
-#include "confdefs.h"
-
-	#include <fox/fxver.h>
-	int main(int argc, char** argv) {
-		return (FOX_MAJOR == 1 && FOX_MINOR == 0) ? 0 : -1;
-	}
-	
-EOF
-if { (eval echo configure:6138: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
-then
-  echo "$ac_t""yes" 1>&6
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -fr conftest*
-  echo "$ac_t""no" 1>&6; { echo "configure: error: Incompatible FOX version" 1>&2; exit 1; }
-fi
-rm -fr conftest*
-fi
-
-
-#
 # End
 #
 CPPFLAGS=$FOX_OLD_CPPFLAGS
@@ -6162,6 +6128,179 @@ cross_compiling=$ac_cv_prog_cc_cross
 
 
 
+# Finally, execute ACTION-IF-OK/ACTION-IF-NOT-OK:
+if test x"$have_FOX" = xyes; then
+        " "
+        :
+else
+        
+        :
+fi
+
+# 1 = FOX MAJOR VERSION
+# 0 = FOX_MINOR_VERSION
+#  = ACTION-IF-OK
+#  = ACTION-IF-NOT-OK
+
+#
+# FLAGS backup
+#
+FOX_OLD_CPPFLAGS=$CPPFLAGS
+FOX_OLD_LDFLAGS=$LDFLAGS
+
+
+#
+# Temporary FLAGS setting
+#
+CPPFLAGS="$CPPFLAGS $PTHREAD_CFLAGS -I${FOX_INCLUDE_DIR}"
+LDFLAGS="$LDFLAGS -L${FOX_LIB_DIR} -lFOX"
+ac_ext=c
+# CFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='${CC-cc} -c $CFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
+ac_link='${CC-cc} -o conftest${ac_exeext} $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+cross_compiling=$ac_cv_prog_cc_cross
+
+
+#
+# Check Fox version
+#
+echo $ac_n "checking FOX version 1.0.x""... $ac_c" 1>&6
+echo "configure:6170: checking FOX version 1.0.x" >&5
+if test "$cross_compiling" = yes; then
+  echo "configure: warning: Cross compiling" 1>&2
+else
+  cat > conftest.$ac_ext <<EOF
+#line 6175 "configure"
+#include "confdefs.h"
+
+	#include <fox/fxver.h>
+	int main(int argc, char** argv) {
+		return (FOX_MAJOR == 1 && FOX_MINOR == 0) ? 0 : -1;
+	}
+	
+EOF
+if { (eval echo configure:6184: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  echo "$ac_t""yes" 1>&6; check_libfox_version_ok=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  echo "$ac_t""no" 1>&6
+fi
+rm -fr conftest*
+fi
+
+
+#
+# Restore FLAGS
+#
+CPPFLAGS=$FOX_OLD_CPPFLAGS
+LDFLAGS=$FOX_OLD_LDFLAGS
+ac_ext=c
+# CFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='${CC-cc} -c $CFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
+ac_link='${CC-cc} -o conftest${ac_exeext} $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+cross_compiling=$ac_cv_prog_cc_cross
+
+
+# Finally, execute ACTION-IF-OK/ACTION-IF-NOT-OK:
+if test x"$check_libfox_version_ok" = xyes; then
+        cat >> confdefs.h <<\EOF
+#define HAVE_FOX_1_0 1
+EOF
+
+        :
+else
+        check_libfox_version_ok=no
+        
+fi
+
+if test x"$check_libfox_version_ok" = xno; then
+	# 1 = FOX MAJOR VERSION
+# 1 = FOX_MINOR_VERSION
+#  = ACTION-IF-OK
+# { echo "configure: error: Incompatible FOX version" 1>&2; exit 1; } = ACTION-IF-NOT-OK
+
+#
+# FLAGS backup
+#
+FOX_OLD_CPPFLAGS=$CPPFLAGS
+FOX_OLD_LDFLAGS=$LDFLAGS
+
+
+#
+# Temporary FLAGS setting
+#
+CPPFLAGS="$CPPFLAGS $PTHREAD_CFLAGS -I${FOX_INCLUDE_DIR}"
+LDFLAGS="$LDFLAGS -L${FOX_LIB_DIR} -lFOX"
+ac_ext=c
+# CFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='${CC-cc} -c $CFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
+ac_link='${CC-cc} -o conftest${ac_exeext} $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+cross_compiling=$ac_cv_prog_cc_cross
+
+
+#
+# Check Fox version
+#
+echo $ac_n "checking FOX version 1.1.x""... $ac_c" 1>&6
+echo "configure:6252: checking FOX version 1.1.x" >&5
+if test "$cross_compiling" = yes; then
+  echo "configure: warning: Cross compiling" 1>&2
+else
+  cat > conftest.$ac_ext <<EOF
+#line 6257 "configure"
+#include "confdefs.h"
+
+	#include <fox/fxver.h>
+	int main(int argc, char** argv) {
+		return (FOX_MAJOR == 1 && FOX_MINOR == 1) ? 0 : -1;
+	}
+	
+EOF
+if { (eval echo configure:6266: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  echo "$ac_t""yes" 1>&6; check_libfox_version_ok=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  echo "$ac_t""no" 1>&6
+fi
+rm -fr conftest*
+fi
+
+
+#
+# Restore FLAGS
+#
+CPPFLAGS=$FOX_OLD_CPPFLAGS
+LDFLAGS=$FOX_OLD_LDFLAGS
+ac_ext=c
+# CFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='${CC-cc} -c $CFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
+ac_link='${CC-cc} -o conftest${ac_exeext} $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+cross_compiling=$ac_cv_prog_cc_cross
+
+
+# Finally, execute ACTION-IF-OK/ACTION-IF-NOT-OK:
+if test x"$check_libfox_version_ok" = xyes; then
+        cat >> confdefs.h <<\EOF
+#define HAVE_FOX_1_1 1
+EOF
+
+        :
+else
+        check_libfox_version_ok=no
+        { echo "configure: error: Incompatible FOX version" 1>&2; exit 1; }
+fi
+
+fi
 
 trap '' 1 2 15
 cat > confcache <<\EOF
